apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f Compose/docker-compose.yaml --volumes configMap
    kompose.version: 1.21.0 ()
  labels:
    io.kompose.service: pingfederate
  name: pingfederate
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: pingfederate
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f Compose/docker-compose.yaml --volumes configMap
        kompose.version: 1.21.0 ()
  
      labels:
        io.kompose.service: pingfederate
    spec:
      containers:
      - args:
        - wait-for
        - pingdirectory:1636
        - -t
        - "7200"
        - --
        - entrypoint.sh
        - start-server
        env:
        - name: PF_LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              key: PF_LOG_LEVEL
              name: env-vars
        - name: PING_IDENTITY_PASSWORD
          valueFrom:
            configMapKeyRef:
              key: PING_IDENTITY_PASSWORD
              name: env-vars
        - name: USER_BASE_DN
          valueFrom:
            configMapKeyRef:
              key: USER_BASE_DN
              name: env-vars
        - name: PING_IDENTITY_ACCEPT_EULA
          valueFrom:
            configMapKeyRef:
              key: PING_IDENTITY_ACCEPT_EULA
              name: env-vars
        - name: SERVER_PROFILE_PATH
          value: pingfederate
        - name: SERVER_PROFILE_URL
          value: https://github.com/pingidentity/Customer360.git
        - name: PF_ADMIN_MODE
          valueFrom:
            configMapKeyRef:
              key: PF_ADMIN_MODE
              name: env-vars
        - name: PF_ADMIN_HOSTNAME
          valueFrom:
            configMapKeyRef:
              key: PF_ADMIN_HOSTNAME
              name: env-vars
        - name: PF_ADMIN_PORT
          valueFrom:
            configMapKeyRef:
              key: PF_ADMIN_PORT
              name: env-vars
        - name: ADMIN_CLIENT_ID
          valueFrom:
            configMapKeyRef:
              key: ADMIN_CLIENT_ID
              name: env-vars
        - name: ADMIN_CLIENT_SECRET
          valueFrom:
            configMapKeyRef:
              key: ADMIN_CLIENT_SECRET
              name: env-vars
        - name: ADMIN_CLIENT_ISSUER
          valueFrom:
            configMapKeyRef:
              key: ADMIN_CLIENT_ISSUER
              name: env-vars
        - name: ADMIN_CLIENT_AUTHZ
          valueFrom:
            configMapKeyRef:
              key: ADMIN_CLIENT_AUTHZ
              name: env-vars
        - name: ADMIN_CLIENT_TOKEN
          valueFrom:
            configMapKeyRef:
              key: ADMIN_CLIENT_TOKEN
              name: env-vars
        - name: ADMIN_CLIENT_USERINFO
          valueFrom:
            configMapKeyRef:
              key: ADMIN_CLIENT_USERINFO
              name: env-vars
        - name: ADMIN_CLIENT_LOGOFF
          valueFrom:
            configMapKeyRef:
              key: ADMIN_CLIENT_LOGOFF
              name: env-vars
        image: pingidentity/pingfederate:latest
        imagePullPolicy: "IfNotPresent"
        name: pingfederate
        ports:
        - containerPort: 9031
        - containerPort: 9999
        resources: {}
        envFrom:
          - secretRef:
              name: devops-secret
      restartPolicy: Always
      serviceAccountName: ""
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f Compose/docker-compose.yaml --volumes configMap
    kompose.version: 1.21.0 ()
  labels:
    io.kompose.service: pingfederate
  name: pingfederate
spec:
  ports:
  - name: "9031"
    port: 9031
    targetPort: 9031
  - name: "443"
    port: 443
    targetPort: 443
  - name: "9999"
    port: 9999
    targetPort: 9999
  selector:
    io.kompose.service: pingfederate
