## Product Specific values
# DevOps Keys and \ or License files can be applied to the container
# License files should be injected into your kubernetes namespace as secrets:
  # (Eval)   ping-devops generate license {product} | kubectl apply -f -
  # (Real)   ping-devops generate license-secret {license file} | kubectl apply -f -
pingfederate:
  pingdevops:
    license:
      # If set to false, licenses must be mounted as secrets
      useDevOpsKey: false
      ## Accept the Ping EULA -- "YES" | (default) "NO" (Note: this will not allow Products to launch)
      acceptEULA: "NO"

pingdirectory:
  pingdevops:
  # Variables used to determine licensing for the stack
    license:
      # If set to false, licenses must be mounted as secrets
      useDevOpsKey: false
      ## Accept the Ping EULA -- "YES" | (default) "NO" (Note: this will not allow Products to launch)
      acceptEULA: "NO"

pingdatasync:
  pingdevops:
    # Variables used to determine licensing for the stack
    license:
      # If set to false, licenses must be mounted as secrets
      useDevOpsKey: false
      ## Accept the Ping EULA -- "YES" | (default) "NO" (Note: this will not allow Products to launch)
      acceptEULA: "NO"

pingcentral:
  pingdevops:
    # Variables used to determine licensing for the stack
    license:
      # If set to false, licenses must be mounted as secrets
      useDevOpsKey: false
      ## Accept the Ping EULA -- "YES" | (default) "NO" (Note: this will not allow Products to launch)
      acceptEULA: "NO"